### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by Norskan** [SharedMediaManagerGroup/SharedMediaManager#4]
### Basic Readme
- [x] referenz to gitflow
- [x] referenz to code convetions or write own
- [x] version handling

**Comment by communityFabian** [comment]
Code conventions i only care for this:

K&R braces style:

```
if (x == y) {
    x++;
    foo();
} else {
    x--;
    bar();
}
```

Indent/Tab size (Visual studio 2015): 2 (?)

**Comment by Norskan** [comment]
okay thats fine with me. intent/Tap size 2 would be fine with me and also replace tabs with spaces
